"""Adaptive Index Evolution for scalability.

Per XCUT-06 and FEATURES.md (Memex pattern):
- flat (<=50 pages): simple list
- hierarchical (51-200 pages): category tree
- indexed (>200 pages): concept clustering + routing
"""
from __future__ import annotations

import time
from dataclasses import dataclass
from enum import Enum
from pathlib import Path
from typing import TYPE_CHECKING, Any

import yaml

if TYPE_CHECKING:
    from saw.config.settings import WikiSettings


class IndexMode(Enum):
    """Index mode based on knowledge base scale.

    FLAT: <=50 pages - simple list
    HIERARCHICAL: 51-200 pages - category tree
    INDEXED: >200 pages - concept clustering + routing
    """
    FLAT = "flat"
    HIERARCHICAL = "hierarchical"
    INDEXED = "indexed"


@dataclass
class IndexUpgradeResult:
    """Result of an index upgrade operation.

    Attributes:
        from_mode: Previous index mode.
        to_mode: New index mode.
        pages_processed: Number of pages processed during upgrade.
        duration_ms: Duration of upgrade in milliseconds.
        new_structure_path: Path to the new index structure file.
    """
    from_mode: IndexMode
    to_mode: IndexMode
    pages_processed: int
    duration_ms: int
    new_structure_path: Path


@dataclass
class ConceptCluster:
    """A cluster of conceptually related pages.

    Attributes:
        name: Cluster name.
        page_paths: List of page paths in the cluster.
        summary: Cluster summary (generated by LLM).
        keywords: Keywords for this cluster.
    """
    name: str
    page_paths: list[str]
    summary: str = ""
    keywords: list[str] | None = None


class AdaptiveIndexManager:
    """Manages adaptive index evolution based on page count.

    Per XCUT-06: Automatic upgrade at thresholds:
    - <=50 pages: FLAT mode (simple list)
    - 51-200 pages: HIERARCHICAL mode (category tree)
    - >200 pages: INDEXED mode (concept clustering + routing)

    Per FEATURES.md (Memex pattern): Index evolves as KB grows.
    """

    # Thresholds for mode transitions
    HIERARCHICAL_THRESHOLD = 50
    INDEXED_THRESHOLD = 200

    def __init__(
        self,
        wiki_repo,
        config: WikiSettings,
    ) -> None:
        """Initialize adaptive index manager.

        Args:
            wiki_repo: Wiki repository for page access.
            config: Wiki settings.
        """
        self._wiki_repo = wiki_repo
        self._config = config
        self._thresholds = {
            IndexMode.HIERARCHICAL: self.HIERARCHICAL_THRESHOLD,
            IndexMode.INDEXED: self.INDEXED_THRESHOLD,
        }

    def get_mode(self) -> IndexMode:
        """Determine current index mode based on page count.

        Returns:
            IndexMode enum value based on current page count.
        """
        try:
            page_count = self._wiki_repo.count()
        except Exception:
            page_count = 0

        if page_count <= self._thresholds[IndexMode.HIERARCHICAL]:
            return IndexMode.FLAT
        elif page_count <= self._thresholds[IndexMode.INDEXED]:
            return IndexMode.HIERARCHICAL
        else:
            return IndexMode.INDEXED

    def check_upgrade(self) -> bool:
        """Check if index needs upgrade based on current state.

        Returns:
            True if mode in config differs from actual mode.
        """
        current_mode_str = getattr(self._config, "index_mode", "flat")
        try:
            current_mode = IndexMode(current_mode_str)
        except ValueError:
            current_mode = IndexMode.FLAT

        actual_mode = self.get_mode()
        return current_mode != actual_mode

    def upgrade_index(self) -> IndexUpgradeResult | None:
        """Migrate index structure to appropriate mode.

        Returns:
            IndexUpgradeResult if upgrade performed, None if no upgrade needed.
        """
        if not self.check_upgrade():
            return None

        start_time = time.time()

        current_mode_str = getattr(self._config, "index_mode", "flat")
        try:
            from_mode = IndexMode(current_mode_str)
        except ValueError:
            from_mode = IndexMode.FLAT

        to_mode = self.get_mode()
        pages_processed = 0

        try:
            pages_processed = self._wiki_repo.count()
        except Exception:
            pass

        # Perform upgrade based on target mode
        if to_mode == IndexMode.HIERARCHICAL:
            new_path = self._upgrade_to_hierarchical()
        elif to_mode == IndexMode.INDEXED:
            new_path = self._upgrade_to_indexed()
        else:
            new_path = self._create_flat_index()

        duration_ms = int((time.time() - start_time) * 1000)

        return IndexUpgradeResult(
            from_mode=from_mode,
            to_mode=to_mode,
            pages_processed=pages_processed,
            duration_ms=duration_ms,
            new_structure_path=new_path,
        )

    def build_category_tree(self) -> dict[str, list[str]]:
        """Build hierarchical category structure.

        Groups pages by their top-level namespace (concepts, entities, etc.).

        Returns:
            Dict mapping category name to list of page paths.
        """
        tree: dict[str, list[str]] = {}

        try:
            pages = self._wiki_repo.list_pages()

            for page_path in pages:
                parts = page_path.split("/")
                if len(parts) > 1:
                    category = parts[0]
                else:
                    category = "uncategorized"

                if category not in tree:
                    tree[category] = []
                tree[category].append(page_path)
        except Exception:
            pass

        return tree

    def build_concept_clusters(self) -> list[ConceptCluster]:
        """Build concept-based clustering for indexed mode.

        Uses embedding similarity to cluster related pages.
        Falls back to namespace-based clustering if embeddings unavailable.

        Returns:
            List of ConceptCluster objects.
        """
        clusters: list[ConceptCluster] = []

        # For now, use namespace-based clustering as fallback
        # In production, would use embeddings for semantic clustering
        tree = self.build_category_tree()

        for category, pages in tree.items():
            cluster = ConceptCluster(
                name=category,
                page_paths=pages,
                summary=f"Pages related to {category}",
                keywords=[category],
            )
            clusters.append(cluster)

        return clusters

    def _create_flat_index(self) -> Path:
        """Create flat index structure.

        Returns:
            Path to the created index file.
        """
        index_path = self._get_index_path(IndexMode.FLAT)

        pages = self._wiki_repo.list_pages()

        data = {
            "mode": "flat",
            "pages": pages,
        }

        index_path.parent.mkdir(parents=True, exist_ok=True)
        with open(index_path, "w", encoding="utf-8") as f:
            yaml.dump(data, f, default_flow_style=False)

        return index_path

    def _upgrade_to_hierarchical(self) -> Path:
        """Upgrade to hierarchical mode with category tree.

        Returns:
            Path to the created index file.
        """
        index_path = self._get_index_path(IndexMode.HIERARCHICAL)

        tree = self.build_category_tree()

        data = {
            "mode": "hierarchical",
            "tree": tree,
            "categories": list(tree.keys()),
        }

        index_path.parent.mkdir(parents=True, exist_ok=True)
        with open(index_path, "w", encoding="utf-8") as f:
            yaml.dump(data, f, default_flow_style=False)

        return index_path

    def _upgrade_to_indexed(self) -> Path:
        """Upgrade to indexed mode with concept clusters.

        Returns:
            Path to the created index file.
        """
        index_path = self._get_index_path(IndexMode.INDEXED)

        clusters = self.build_concept_clusters()

        data = {
            "mode": "indexed",
            "clusters": [
                {
                    "name": c.name,
                    "pages": c.page_paths,
                    "summary": c.summary,
                    "keywords": c.keywords or [],
                }
                for c in clusters
            ],
        }

        index_path.parent.mkdir(parents=True, exist_ok=True)
        with open(index_path, "w", encoding="utf-8") as f:
            yaml.dump(data, f, default_flow_style=False)

        return index_path

    def _get_index_path(self, mode: IndexMode) -> Path:
        """Get path for index file based on mode.

        Args:
            mode: Index mode.

        Returns:
            Path to index file.
        """
        wiki_path = getattr(self._config, "path", Path("."))
        saw_dir = Path(wiki_path) / ".saw"

        if mode == IndexMode.FLAT:
            return saw_dir / "index_flat.yaml"
        elif mode == IndexMode.HIERARCHICAL:
            return saw_dir / "index_hierarchical.yaml"
        else:
            return saw_dir / "index_indexed.yaml"
